# Generated by Django 4.1.7 on 2023-03-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='type',
            field=models.CharField(default='CLOTH', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
